spring:
  application:
    name: API-GATEWAY

 # cloud:
  #  gateway:
   #   routes:
     #  id: CUSTOMER-API
    #   uri: lb://CUSTOMER-API
     #  predicates:
      #  -Path="/customer/**"

server:
  port: 9096

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /test-service/v3/api-docs
        name: Test Service