spring:
  application:
    name: API-GATEWAY

 # cloud:
  #  gateway:
   #   routes:
     #  id: CUSTOMER-API
    #   uri: lb://CUSTOMER-API
     #  predicates:
      #  -Path="/customer/**"

server:
  port: 9096

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka